-- CreateTable
CREATE TABLE `notification_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(256) NOT NULL,
    `value` VARCHAR(500) NOT NULL,
    `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
